apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-web-app-deployment
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: redweb
        image: khatab24/simpleweb:latest
        ports:
        - containerPort: 3000
